config/routes.rb
Rails.application.routes.draw do
  root "chat#index"

  scope "/chat", as: "chat" do
    get "/", to: "chat#enter"
    post "/", to: "chat#create"

    scope ":room_name" do
      get "/", to: "chat#show", as: :show

      get "users/new", to: "users#new", as: :users_new
      post "users/new", to: "users#create", as: :users_create

      post "create", to: "messages#create", as: :create
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :content, presence: true, length: { minimum: 1, maximum: 1024 }

  after_create_commit do
    broadcast_append_to room, target: "messages", partial: "messages/message", locals: { message: self, from_stream: true }
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy

  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users

  before_create :set_name

  private

  def set_name
    self.name = SecureRandom.hex(4)
  end
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :user_id, uniqueness: { scope: :room_id }

  after_create_commit do
    broadcast_append_later_to(
      "online_users_room_#{room.name}",
      target: "users",
      partial: "users/user",
      locals: { user: user }
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages, dependent: :destroy

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  allow_browser versions: :modern
  helper_method :current_user

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  private

  def record_not_found
    redirect_to root_path, alert: "Registro não encontrado"
  end
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  before_action :fetch_user_from_session, only: :show
  def index
    @room = Room.new
  end

  def show
    @room = Room.find_by!(name: params[:room_name])
    @messages = @room.messages.order(:created_at)

    RoomUser.find_or_create_by!(user: current_user, room: @room)
  end

  def create
    @room = Room.new

    if @room.save
      redirect_to chat_show_path(@room.name)
    else
      redirect_to root_path, alert: "Erro ao criar chat"
    end
  end

  def enter
    if Room.find_by(name: params[:room_name])
      redirect_to chat_show_path(params[:room_name])
    else
      redirect_to root_path, alert: "Código de chat inválido"
    end
  end

  private

  def fetch_user_from_session
    unless session[:user_id] && User.exists?(session[:user_id])
      redirect_to chat_users_new_path(room_name: params[:room_name])
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.new(
      content: params[:content],
      user: User.find_by(id: session[:user_id]),
      room: Room.find_by(name: params[:room_name])
    )

    if @message.save
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.append(
            "messages", partial: "messages/message", locals: { message: @message, from_stream: false }
          )
        end
        format.html { redirect_to chat_show_path(params[:room_name]) }
      end
    else
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.update(
            "form-errors",
            partial: "shared/flash", locals: { alert: "Erro ao enviar mensagem" }
          )
        end
        format.html do
          flash[:alert] = "Erro ao enviar mensagem"
          redirect_to chat_show_path(params[:room_name])
        end
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(name: params[:user_name])

    if @user.save
      session[:user_id] = @user.id
      redirect_to chat_show_path(params[:room_name])
    else
      flash[:alert] = "Erro ao criar o usuário"
      render :new, status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chat/index.html.erb
<div class="flex items-center justify-center min-h-screen">
  <div class="w-full max-w-md bg-white rounded-xl shadow p-6 mx-2 dark:bg-gray-800">
    <h5 class="text-2xl font-medium text-gray-900 dark:text-white mb-4 text-center">
      Bem-vindo ao Shat
    </h5>

    <%= form_with url: chat_path, method: :post, class: "my-10" do |f| %>
      <button
        type="submit"
        class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none
        focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600
        dark:hover:bg-blue-700 dark:focus:ring-blue-800"
      >
        Criar novo chat
      </button>
    <% end %>

    <%= form_with url: chat_path, method: :get, class: "space-y-6" do |f| %>
      <div>
        <label
          for="room_name_enter"
          class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
        >
          Código do Chat
        </label>
        <div class="flex items-center space-x-2 rtl:space-x-reverse">
          <%= f.text_field :room_name, id: "room_name_enter",
                           class: "flex-grow bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg
                   focus:ring-blue-500 focus:border-blue-500 block p-2.5 dark:bg-gray-600 dark:border-gray-500
                   dark:placeholder-gray-400 dark:text-white",
                           autocomplete: "off", placeholder: "Exemplo: d67add05", required: true %>
          <button
            type="submit"
            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
          >
            Entrar
          </button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/chat/show.html.erb
<div class="flex flex-col h-[calc(100svh-4.5rem)] sm:h-[calc(100svh-5rem)] mt-[4.5rem] shadow" data-controller="scroll">
  <!-- Cabeçalho do Chat -->
  <div class="flex items-center justify-between p-2 bg-gray-100 dark:bg-gray-700 sm:rounded-t-lg">
    <div class="flex items-center">
      <!-- Botão de Voltar -->
      <%= link_to root_path do %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="size-5 text-gray-700 dark:text-white">
          <path fill-rule="evenodd" d="M7.793 2.232a.75.75 0 0 1-.025 1.06L3.622 7.25h10.003a5.375 5.375 0 0 1 0 10.75H10.75a.75.75 0 0 1 0-1.5h2.875a3.875 3.875 0 0 0 0-7.75H3.622l4.146 3.957a.75.75 0 0 1-1.036 1.085l-5.5-5.25a.75.75 0 0 1 0-1.085l5.5-5.25a.75.75 0 0 1 1.06.025Z" clip-rule="evenodd"/>
        </svg>
      <% end %>
    </div>
    <div class="flex items-center" data-controller="dialog" data-action="click->dialog#backdropClose">
      <%= render partial: "shared/chat_modal" %>
      <button type="button" data-action="dialog#open" class="flex items-center text-white text-lg text-center">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="size-5">
          <path fill-rule="evenodd" d="M7.84 1.804A1 1 0 0 1 8.82 1h2.36a1 1 0 0 1 .98.804l.331 1.652a6.993 6.993 0 0 1 1.929 1.115l1.598-.54a1 1 0 0 1 1.186.447l1.18 2.044a1 1 0 0 1-.205 1.251l-1.267 1.113a7.047 7.047 0 0 1 0 2.228l1.267 1.113a1 1 0 0 1 .206 1.25l-1.18 2.045a1 1 0 0 1-1.187.447l-1.598-.54a6.993 6.993 0 0 1-1.929 1.115l-.33 1.652a1 1 0 0 1-.98.804H8.82a1 1 0 0 1-.98-.804l-.331-1.652a6.993 6.993 0 0 1-1.929-1.115l-1.598.54a1 1 0 0 1-1.186-.447l-1.18-2.044a1 1 0 0 1 .205-1.251l1.267-1.114a7.05 7.05 0 0 1 0-2.227L1.821 7.773a1 1 0 0 1-.206-1.25l1.18-2.045a1 1 0 0 1 1.187-.447l1.598.54A6.992 6.992 0 0 1 7.51 3.456l.33-1.652ZM10 13a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z" clip-rule="evenodd"/>
        </svg>
      </button>
    </div>
  </div>

  <!-- Mensagens -->
  <div class="flex-1 overflow-y-auto p-4 space-y-4 bg-white dark:bg-gray-800" data-scroll-target="messages">
    <%= turbo_stream_from @room %>
    <div id="messages">
      <% @messages.each do |message| %>
        <%= render partial: 'messages/message', locals: { message: message, from_stream: current_user != message.user } %>
      <% end %>
    </div>
  </div>
  <div id="form-errors"></div>

  <!-- Formulário de Envio -->
  <div class="px-4 pt-4 pb-2 bg-gray-100 sm:rounded-b-lg dark:bg-gray-700" data-controller="character-counter" data-character-counter-countdown-value="true">
    <%= form_with url: chat_create_path, method: :post, id: "message-form", local: true, html: { class: 'flex items-center gap-4' }, data: { controller: "clear", action: "turbo:submit-end->clear#clearInput" } do |form| %>
      <%= form.text_field :content, placeholder: "Digite sua mensagem...",
                          autocomplete: "off", id: "message-input",
                          class: "flex-1 px-4 py-3 border border-gray-300 dark:border-none rounded-lg shadow-sm bg-white
                          text-black placeholder-gray-500 focus:outline-none focus:ring focus:border-blue-500 resize-none
                          dark:bg-gray-600 dark:text-white dark:placeholder-gray-400 w-full",
                          data: { character_counter_target: "input", clear_target: "input" }, maxlength: "1024"
      %>
      <button
        type="submit"
        class="w-12 h-12 flex items-center justify-center bg-blue-700 hover:bg-blue-800 text-white rounded-full shadow-md
        focus:outline-none focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700
      dark:focus:ring-blue-800"
      >
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-5 h-5">
          <path d="M3.478 2.404a.75.75 0 0 0-.926.941l2.432 7.905H13.5a.75.75 0 0 1 0 1.5H4.984l-2.432 7.905a.75.75 0 0 0 .926.94 60.519 60.519 0 0 0 18.445-8.986.75.75 0 0 0 0-1.218A60.517 60.517 0 0 0 3.478 2.404Z"/>
        </svg>
      </button>
    <% end %>
    <p class="text-sm text-gray-600 dark:text-gray-300 mt-2">
      Caracteres restantes:
      <strong data-character-counter-target="counter" id="character-counter"></strong>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title><%= content_for(:title) || "Turbo Chat" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="bg-zinc-50 dark:bg-gray-600">
  <%= render partial: "shared/flash", locals: { notice: flash[:notice], alert: flash[:alert] } %>
  <header>
    <nav class="bg-white text-gray-800 dark:text-white dark:bg-gray-800 w-full z-20 top-0 start-0 shadow fixed">
      <div class="max-w-5xl flex flex-wrap items-center justify-between mx-auto p-4">
        <a href="/" class="flex items-center space-x-3">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="currentColor"
            class="size-6"
          >
            <path d="M4.913 2.658c2.075-.27 4.19-.408 6.337-.408 2.147 0 4.262.139 6.337.408 1.922.25 3.291 1.861 3.405 3.727a4.403 4.403 0 0 0-1.032-.211 50.89 50.89 0 0 0-8.42 0c-2.358.196-4.04 2.19-4.04 4.434v4.286a4.47 4.47 0 0 0 2.433 3.984L7.28 21.53A.75.75 0 0 1 6 21v-4.03a48.527 48.527 0 0 1-1.087-.128C2.905 16.58 1.5 14.833 1.5 12.862V6.638c0-1.97 1.405-3.718 3.413-3.979Z"/>
            <path d="M15.75 7.5c-1.376 0-2.739.057-4.086.169C10.124 7.797 9 9.103 9 10.609v4.285c0 1.507 1.128 2.814 2.67 2.94 1.243.102 2.5.157 3.768.165l2.782 2.781a.75.75 0 0 0 1.28-.53v-2.39l.33-.026c1.542-.125 2.67-1.433 2.67-2.94v-4.286c0-1.505-1.125-2.811-2.664-2.94A49.392 49.392 0 0 0 15.75 7.5Z"/>
          </svg>
          <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">
          Turbo Chat
        </span>
        </a>
      </div>
    </nav>
  </header>
  <main class="max-w-5xl mx-auto">
    <%= yield %>
  </main>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="flex items-start mb-4" id="<%= dom_id(message) %> on">
  <div class="flex w-full justify-between">
    <div class="flex flex-col gap-1 w-full">
      <!-- Informações do Usuário -->
      <div class="<%= from_stream ? 'flex items-center justify-start space-x-2' : 'flex items-center justify-end space-x-2 rtl:space-x-reverse' %>">
        <span class="text-sm font-semibold text-gray-900 dark:text-white">
          <%= message.user.name %>
        </span>
        <span class="text-sm font-normal text-gray-500 dark:text-gray-400">
          <%= message.created_at.strftime('%H:%M') %>
        </span>
      </div>
      <!-- Conteúdo da Mensagem -->
      <div class="<%= from_stream ? 'leading-1.5 px-3 py-2 bg-gray-200 dark:bg-gray-600 text-gray-900 rounded-e-xl rounded-es-xl dark:bg-gray-700 dark:text-white max-w-[70%] w-fit' : 'leading-1.5 px-3 py-2 bg-blue-600 text-white rounded-l-xl rounded-tr-xl max-w-[70%] w-fit justify-center ml-auto' %>">
        <p class="text-sm font-normal break-words">
          <%= message.content %>
        </p>
      </div>
    </div>
  </div>
</div>
<script>
  document.dispatchEvent(new Event("new_message"));
</script>

app/views/shared/_chat_modal.html.erb
<dialog data-dialog-target="dialog">
  <div class="flex overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative p-4 w-full max-w-md max-h-full">
      <!-- Modal content -->
      <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
        <!-- Modal header -->
        <div class="flex items-center justify-between p-4 border-b rounded-t dark:border-gray-600">
          <h3 class="text-xl font-semibold text-gray-900 dark:text-white">
            Informações
          </h3>
          <button type="button" data-action="dialog#close" autofocus class="end-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white">
            <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
            </svg>
          </button>
        </div>
        <div class="p-4" data-controller="chat" data-chat-room-name-value="<%= @room.name %>" data-chat-user-id-value="<%= current_user.id %>">
          <%= render partial: "shared/copy_to_clipboard", locals: { label_text: "Copiar código da sala", value: @room.name } %>
          <h4 class="text-sm font-semibold text-gray-900 dark:text-white mt-4 mb-2">
            Usuários online na sala:
          </h4>
          <%= turbo_stream_from "online_users_room_#{@room.name}" %>
          <div id="users">
            <% @room.users.each do |user| %>
              <%= render partial: "users/user", locals: { user: } %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</dialog>

app/views/shared/_copy_to_clipboard.html.erb
<div data-controller="clipboard" data-clipboard-success-content-value="Copiado!">
  <div class="mb-2 flex justify-between items-center">
    <label for="room-name" class="text-sm font-semibold text-gray-900 dark:text-white"><%= label_text %>:</label>
  </div>
  <div class="flex">
    <input
      type="text"
      value="<%= value %>"
      readonly
      data-clipboard-target="source"
      class="text-sm bg-gray-50 border rounded-l-lg border-gray-300 text-gray-500 dark:text-gray-400 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400"/>

    <button
      type="button"
      data-action="clipboard#copy"
      data-clipboard-target="button"
      class="text-sm bg-blue-700 text-white px-4 py-2 rounded-r-lg hover:bg-blue-800 dark:bg-blue-600 dark:hover:bg-blue-700">
      Copiar
    </button>
  </div>
</div>

app/views/shared/_flash.html.erb
<% if notice %>
  <div
    id="toast-success"
    class="absolute top-20 right-5 flex items-center w-full max-w-xs p-4 mb-4 text-gray-500 bg-white
    rounded-lg shadowdark:text-gray-400 dark:bg-gray-800 transition transform duration-500"
    role="alert"
    data-controller="notification"
    data-transition-enter-from="opacity-0 translate-x-6"
    data-transition-enter-to="opacity-100 translate-x-0"
    data-transition-leave-from="opacity-100 translate-x-0"
    data-transition-leave-to="opacity-0 translate-x-6"
  >
    <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-green-500 bg-green-100 rounded-lg dark:bg-green-800 dark:text-green-200">
      <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z"/>
      </svg>
      <span class="sr-only">Check icon</span>
    </div>
    <div class="ms-3 text-sm font-normal"><%= notice %></div>
    <button type="button" data-action="notification#hide" class="ms-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex items-center justify-center h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700" data-dismiss-target="#toast-success" aria-label="Close">
      <span class="sr-only">Close</span>
      <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
      </svg>
    </button>
  </div>
  <% flash.discard(:notice) %>
<% elsif alert %>
  <div
    id="toast-danger"
    class="absolute top-20 right-5 flex items-center w-full max-w-xs p-4 mb-4 text-gray-500 bg-white
    rounded-lg shadow dark:text-gray-400 dark:bg-gray-800 transition transform duration-500"
    data-controller="notification"
    data-transition-enter-from="opacity-0 translate-x-6"
    data-transition-enter-to="opacity-100 translate-x-0"
    data-transition-leave-from="opacity-100 translate-x-0"
    data-transition-leave-to="opacity-0 translate-x-6"
    role="alert"
  >
    <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-red-500 bg-red-100 rounded-lg dark:bg-red-800 dark:text-red-200">
      <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 11.793a1 1 0 1 1-1.414 1.414L10 11.414l-2.293 2.293a1 1 0 0 1-1.414-1.414L8.586 10 6.293 7.707a1 1 0 0 1 1.414-1.414L10 8.586l2.293-2.293a1 1 0 0 1 1.414 1.414L11.414 10l2.293 2.293Z"/>
      </svg>
      <span class="sr-only">Error icon</span>
    </div>
    <div class="ms-3 text-sm font-normal"><%= alert %></div>
    <button type="button" data-action="notification#hide" class="ms-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex items-center justify-center h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700" data-dismiss-target="#toast-danger" aria-label="Close">
      <span class="sr-only">Close</span>
      <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
      </svg>
    </button>
  </div>
  <% flash.discard(:alert) %>
<% end %>

app/views/users/_user.html.erb
<div class="flex items-center p-2" id="<%= dom_id(user) %>">
  <div class="flex-shrink-0 w-10 h-10 bg-blue-600 text-white rounded-full flex items-center justify-center text-lg font-semibold">
    <%= user.name[0].upcase %>
  </div>
  <div class="ml-4">
    <p class="text-sm font-medium text-gray-900 dark:text-gray-100">
      <%= user.name %>
    </p>
  </div>
</div>

app/views/users/new.html.erb
<div class="flex items-center justify-center min-h-screen">
  <div class="w-full max-w-md bg-white rounded-xl shadow p-6 mx-2 dark:bg-gray-800">
    <h5 class="text-2xl font-medium text-gray-900 dark:text-white mb-4 text-center">
      Defina seu nome ou apelido
    </h5>
    <%= form_with url: chat_users_create_path, method: :post, class: "space-y-6" do |f| %>
      <div>
        <label
          for="user_name"
          class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
        >
          Nome ou Apelido
        </label>
        <%= f.text_field :user_name, id: "user_name", placeholder: "Exemplo: João", autocomplete: "off", required: true,
                         class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" %>
      </div>
      <button
        type="submit"
        class="w-full text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-500 font-medium rounded-lg text-sm px-5 py-2.5 text-center"
      >
        Entrar
      </button>
    <% end %>
  </div>
</div>